import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, setDoc, updateDoc, where, type DocumentData } from 'firebase/firestore';
import { deleteObject, getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { createContentCode, fixtureArticles, fixtureServices, fixtureSettings, isContentCode, isSafeContentUrl, isPublishableArticleBody, isValidArticleBody, isValidBenefits, type Service } from '@tian-xin-ge/contracts';
import { firebaseDb, firebaseStorage } from './firebase';
import { adminApiRequest, isServerAdminApiEnabled } from './features/auth/infrastructure/adminApi';

const remote = () => Boolean(firebaseDb);
const serviceIcons: Service['icon'][] = ['lotus', 'oil', 'stone', 'foot', 'flower'];
const serviceFrom = (id: string, row: DocumentData): Service => ({ id, slug: String(row.slug ?? ''), name: String(row.name ?? ''), summary: String(row.summary ?? ''), description: String(row.description ?? ''), imageUrl: String(row.imageUrl ?? row.image_url ?? ''), icon: serviceIcons.includes(row.icon) ? row.icon : 'lotus', durationMinutes: row.durationMinutes == null && row.duration_minutes == null ? undefined : Number(row.durationMinutes ?? row.duration_minutes), price: row.price == null ? undefined : Number(row.price), priceLabel: row.priceLabel ?? row.price_label ? String(row.priceLabel ?? row.price_label) : undefined, sortOrder: Number(row.sortOrder ?? row.sort_order ?? 0), isVisible: Boolean(row.isVisible ?? row.is_visible) });
const resultOk = (id?: string) => id ? { ok: true as const, mode: 'firebase' as const, id } : { ok: true as const, mode: 'firebase' as const };
const localStorageJson = <T,>(key: string): T | null => { if (typeof window === 'undefined') return null; try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : null; } catch { return null; } };

export async function loadServices() {
  if (!firebaseDb) return null;
  try { const snapshot = await getDocs(query(collection(firebaseDb, 'services'), orderBy('sortOrder'))); return snapshot.docs.map((item) => serviceFrom(item.id, item.data())); } catch { return null; }
}
export async function saveService(service: Service) {
  if (!isSafeContentUrl(service.imageUrl, true)) return { ok: false as const, mode: 'local' as const, error: '圖片必須使用 HTTPS 或站內素材路徑' };
  if (!firebaseDb) return resultOk();
  const slug = isContentCode(service.slug) ? service.slug : createContentCode();
  const payload = { slug, name: service.name, summary: service.summary, description: service.description, imageUrl: service.imageUrl, icon: service.icon, durationMinutes: service.durationMinutes ?? null, price: service.price ?? null, priceLabel: service.priceLabel ?? null, sortOrder: service.sortOrder, isVisible: service.isVisible, updatedAt: new Date().toISOString() };
  try { if (!service.id.startsWith('local-')) { await updateDoc(doc(firebaseDb, 'services', service.id), payload); return resultOk(service.id); } const created = await addDoc(collection(firebaseDb, 'services'), { ...payload, createdAt: new Date().toISOString() }); return resultOk(created.id); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '服務儲存失敗' }; }
}
export async function deleteService(id: string) { if (!firebaseDb || id.startsWith('local-')) return resultOk(); try { await deleteDoc(doc(firebaseDb, 'services', id)); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '服務刪除失敗' }; } }

export type AdminMessage = { id: string; name: string; phone: string; email?: string; message: string; status: 'unread' | 'handled'; note?: string; createdAt: string };
export type AdminMedia = { id: string; name: string; url: string; alt: string; mimeType: string; size: number; storagePath?: string; width?: number; height?: number };
export async function loadMessages(): Promise<AdminMessage[] | null> { if (!firebaseDb) return null; try { const snapshot = await getDocs(query(collection(firebaseDb, 'contact_messages'), orderBy('createdAt', 'desc'))); return snapshot.docs.map((item) => { const row = item.data(); return { id: item.id, name: String(row.name ?? ''), phone: String(row.phone ?? ''), email: row.email ? String(row.email) : undefined, message: String(row.message ?? ''), status: row.status === 'handled' ? 'handled' : 'unread', note: row.note ? String(row.note) : undefined, createdAt: String(row.createdAt ?? '') }; }); } catch { return null; } }
export async function saveMessage(message: Pick<AdminMessage, 'id' | 'status' | 'note'>) { if (!firebaseDb || message.id.startsWith('local-')) return resultOk(); try { await updateDoc(doc(firebaseDb, 'contact_messages', message.id), { status: message.status, note: message.note || '', updatedAt: new Date().toISOString() }); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '留言儲存失敗' }; } }
export async function markMessageHandled(id: string, note?: string) { return saveMessage({ id, status: 'handled', note }); }
export async function deleteMessage(id: string) { if (!firebaseDb || id.startsWith('local-')) return resultOk(); try { await deleteDoc(doc(firebaseDb, 'contact_messages', id)); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '留言刪除失敗' }; } }

export async function loadMedia(): Promise<AdminMedia[] | null> { if (isServerAdminApiEnabled()) { const result = await adminApiRequest<{ items: AdminMedia[] }>('/media'); return result.ok ? result.data.items : null; } if (!firebaseDb) return null; try { const snapshot = await getDocs(query(collection(firebaseDb, 'media_assets'), orderBy('createdAt', 'desc'))); return snapshot.docs.map((item) => { const row = item.data(); return { id: item.id, name: String(row.name ?? ''), url: String(row.url ?? ''), storagePath: row.storagePath ? String(row.storagePath) : undefined, alt: String(row.alt ?? ''), mimeType: String(row.mimeType ?? ''), size: Number(row.size ?? 0), width: row.width == null ? undefined : Number(row.width), height: row.height == null ? undefined : Number(row.height) }; }); } catch { return null; } }
export async function saveMediaAlt(id: string, alt: string) { if (isServerAdminApiEnabled()) { const result = await adminApiRequest(`/media/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ alt: alt.trim().slice(0, 160) }) }); return result.ok ? resultOk(id) : { ok: false as const, mode: 'firebase' as const, error: result.error }; } if (!firebaseDb || id.startsWith('local-')) return resultOk(); try { await updateDoc(doc(firebaseDb, 'media_assets', id), { alt: alt.trim().slice(0, 160), updatedAt: new Date().toISOString() }); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '替代文字儲存失敗' }; } }
function localMediaIsInUse(url: string) { const services = localStorageJson<Array<{ imageUrl?: string }>>('txg-services') ?? fixtureServices; if (services.some((item) => item.imageUrl === url)) return true; const articles = localStorageJson<Array<{ coverUrl?: string; body?: string }>>('txg-articles') ?? fixtureArticles; return articles.some((item) => item.coverUrl === url || (typeof item.body === 'string' && item.body.includes(url))); }
async function remoteMediaIsInUse(media: AdminMedia) { if (!firebaseDb) return false; const [services, articles, settings] = await Promise.all([getDocs(collection(firebaseDb, 'services')), getDocs(collection(firebaseDb, 'articles')), getDoc(doc(firebaseDb, 'site_settings', 'singleton'))]); const target = media.id; const usedByService = services.docs.some((item) => item.data().imageUrl === media.url || item.data().imageMediaId === target); const usedByArticle = articles.docs.some((item) => { const row = item.data(); return row.coverUrl === media.url || row.coverMediaId === target || JSON.stringify(row.body ?? []).includes(media.url) || JSON.stringify(row.body ?? []).includes(target); }); const settingsData = settings.data() ?? {}; return usedByService || usedByArticle || Object.values(settingsData).some((value) => value === media.url || value === target); }
export async function deleteMedia(media: Pick<AdminMedia, 'id' | 'url' | 'storagePath'>) { if (isServerAdminApiEnabled()) { const result = await adminApiRequest(`/media/${encodeURIComponent(media.id)}`, { method: 'DELETE' }); return result.ok ? resultOk(media.id) : { ok: false as const, mode: 'firebase' as const, error: result.error }; } if (!firebaseDb || media.id.startsWith('local-')) return localMediaIsInUse(media.url) ? { ok: false as const, mode: 'local' as const, error: '正在使用的素材無法刪除，請先替換所有引用。' } : resultOk(); try { if (await remoteMediaIsInUse(media as AdminMedia)) return { ok: false as const, mode: 'firebase' as const, error: '正在使用的素材無法刪除，請先替換所有引用。' }; await deleteDoc(doc(firebaseDb, 'media_assets', media.id)); if (firebaseStorage && media.storagePath) await deleteObject(ref(firebaseStorage, media.storagePath)); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '素材刪除失敗' }; } }
async function imageDimensions(file: File): Promise<{ width?: number; height?: number }> { if (typeof window === 'undefined') return {}; const url = URL.createObjectURL(file); try { const image = new Image(); const dimensions = await new Promise<{ width: number; height: number }>((resolve, reject) => { image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight }); image.onerror = () => reject(new Error('無法讀取圖片尺寸')); image.src = url; }); return dimensions; } catch { return {}; } finally { URL.revokeObjectURL(url); } }
export async function uploadMedia(file: File, alt = '') { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024) return { ok: false as const, url: '', error: '僅支援 JPEG、PNG、WebP，單檔上限 10 MB' }; const dimensions = await imageDimensions(file); if (isServerAdminApiEnabled()) { const form = new FormData(); form.append('file', file); form.append('alt', alt.trim().slice(0, 160)); const result = await adminApiRequest<{ id: string; url: string; storagePath: string; width?: number; height?: number }>('/media', { method: 'POST', body: form }); return result.ok ? { ok: true as const, mode: 'server' as const, ...result.data } : { ok: false as const, url: '', error: result.error }; } if (!firebaseDb || !firebaseStorage) return { ok: true as const, mode: 'local' as const, url: URL.createObjectURL(file), ...dimensions }; const path = `site-media/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '')}`; try { const object = ref(firebaseStorage, path); await uploadBytes(object, file, { contentType: file.type }); const url = await getDownloadURL(object); const created = await addDoc(collection(firebaseDb, 'media_assets'), { name: file.name, url, storagePath: path, alt: alt.trim().slice(0, 160), mimeType: file.type, size: file.size, width: dimensions.width ?? null, height: dimensions.height ?? null, createdAt: new Date().toISOString() }); return { ok: true as const, mode: 'firebase' as const, id: created.id, url, ...dimensions }; } catch (error) { return { ok: false as const, url: '', error: error instanceof Error ? error.message : '素材上傳失敗' }; } }

export type ManagedArticle = { id: string; slug: string; title: string; category: string; status: string; excerpt: string; seoTitle?: string; seoDescription?: string; type: 'news' | 'blog'; body: string; coverUrl?: string; publishedAt?: string };
export type AdminCategory = { id: string; name: string; type: 'news' | 'blog' };
export async function loadCategories(): Promise<AdminCategory[] | null> { if (!firebaseDb) return null; try { const snapshot = await getDocs(query(collection(firebaseDb, 'article_categories'), orderBy('name'))); return snapshot.docs.map((item) => ({ id: item.id, name: String(item.data().name ?? ''), type: item.data().type === 'blog' ? 'blog' : 'news' })); } catch { return null; } }
export async function saveCategory(category: Omit<AdminCategory, 'id'> & { id?: string }) { if (!firebaseDb) return resultOk(); try { const payload = { name: category.name.trim(), type: category.type, updatedAt: new Date().toISOString() }; if (category.id && !category.id.startsWith('local-')) { await updateDoc(doc(firebaseDb, 'article_categories', category.id), payload); return resultOk(category.id); } const created = await addDoc(collection(firebaseDb, 'article_categories'), { ...payload, createdAt: new Date().toISOString() }); return resultOk(created.id); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '分類儲存失敗' }; } }
export async function deleteCategory(category: string | Pick<AdminCategory, 'id' | 'name'>) { const id = typeof category === 'string' ? category : category.id; if (!firebaseDb || id.startsWith('local-')) return resultOk(); try { const used = await getDocs(query(collection(firebaseDb, 'articles'), where('category', '==', typeof category === 'string' ? id : category.name))); if (!used.empty) return { ok: false as const, mode: 'firebase' as const, error: '使用中的分類無法刪除，請先移動或移除文章。' }; await deleteDoc(doc(firebaseDb, 'article_categories', id)); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '分類刪除失敗' }; } }
export async function loadArticles(): Promise<ManagedArticle[] | null> { if (!firebaseDb) return null; try { const snapshot = await getDocs(query(collection(firebaseDb, 'articles'), orderBy('publishedAt', 'desc'))); return snapshot.docs.map((item) => { const row = item.data(); return { id: item.id, slug: String(row.slug ?? ''), title: String(row.title ?? ''), category: String(row.category ?? ''), status: row.status === 'published' ? 'published' : 'draft', excerpt: String(row.excerpt ?? ''), seoTitle: String(row.seoTitle ?? ''), seoDescription: String(row.seoDescription ?? ''), type: row.type === 'blog' ? 'blog' : 'news', body: JSON.stringify(row.body ?? []), coverUrl: String(row.coverUrl ?? ''), publishedAt: String(row.publishedAt ?? '') }; }); } catch { return null; } }
export async function saveArticle(article: ManagedArticle) { let body: unknown; try { body = JSON.parse(article.body || '[]'); } catch { return { ok: false as const, mode: 'local' as const, error: '正文必須是合法 JSON 陣列' }; } if (!isValidArticleBody(body)) return { ok: false as const, mode: 'local' as const, error: '正文只能使用合法的結構化區塊' }; if (article.status === 'published' && !isPublishableArticleBody(body)) return { ok: false as const, mode: 'local' as const, error: '文章必須先提供正文內容才能發布' }; if (article.coverUrl && !isSafeContentUrl(article.coverUrl, true)) return { ok: false as const, mode: 'local' as const, error: '封面圖片網址不安全' }; if (!firebaseDb) return resultOk(); const slug = isContentCode(article.slug) ? article.slug : createContentCode(); const payload = { slug, title: article.title, category: article.category, excerpt: article.excerpt, seoTitle: article.seoTitle ?? '', seoDescription: article.seoDescription ?? '', type: article.type, status: article.status === 'published' ? 'published' : 'draft', body, coverUrl: article.coverUrl ?? '', publishedAt: article.publishedAt || new Date().toISOString().slice(0, 10), updatedAt: new Date().toISOString() }; try { if (!article.id.startsWith('local-')) { await updateDoc(doc(firebaseDb, 'articles', article.id), payload); return resultOk(article.id); } const created = await addDoc(collection(firebaseDb, 'articles'), { ...payload, createdAt: new Date().toISOString() }); return resultOk(created.id); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '文章儲存失敗' }; } }
export async function deleteArticle(id: string) { if (!firebaseDb || id.startsWith('local-')) return resultOk(); try { await deleteDoc(doc(firebaseDb, 'articles', id)); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '文章刪除失敗' }; } }

const settingKeys = ['brandName', 'phone', 'line', 'address', 'hours', 'mapEmbedUrl', 'instagram', 'facebook', 'youtube', 'logoUrl', 'heroTitle', 'heroSubtitle', 'tagline', 'heroDescription', 'heroBackgroundUrl', 'servicesTitle', 'servicesSubtitle', 'servicesNote', 'servicesBackgroundUrl', 'pricingTitle', 'pricingSubtitle', 'pricingBackgroundUrl', 'newsTitle', 'newsSubtitle', 'newsBackgroundUrl', 'blogTitle', 'blogSubtitle', 'blogBackgroundUrl', 'contactTitle', 'contactLead', 'contactBackgroundUrl', 'benefits', 'pricingBenefits', 'privacy', 'terms', 'seoTitle', 'seoDescription', 'ogImageUrl'] as const;
export async function loadSettings(): Promise<any> { if (!firebaseDb) return null; try { const snapshot = await getDoc(doc(firebaseDb, 'site_settings', 'singleton')); if (!snapshot.exists()) return null; const row = snapshot.data(); return Object.fromEntries(settingKeys.map((key) => [key, row[key] ?? (fixtureSettings as unknown as Record<string, unknown>)[key]])); } catch { return null; } }
export async function saveSettings(value: Record<string, unknown>) { if (!firebaseDb) return resultOk(); if (value.benefits && !isValidBenefits(value.benefits)) return { ok: false as const, mode: 'firebase' as const, error: '特色列格式不正確' }; try { await setDoc(doc(firebaseDb, 'site_settings', 'singleton'), { ...value, updatedAt: new Date().toISOString() }, { merge: true }); return resultOk(); } catch (error) { return { ok: false as const, mode: 'firebase' as const, error: error instanceof Error ? error.message : '網站設定儲存失敗' }; } }
