import { NextResponse } from 'next/server';
import { authorizeAdminRequest } from '@/features/admin-auth/application/authorize';
import { firebaseServer } from '@/lib/firebase-admin';
import { readJsonObject } from '@/lib/request-body';
import { recordAdminAudit } from '@/features/admin-auth/infrastructure/audit';
import { deletedBy, isDeleted } from '@/features/admin-content/deletion';
import { pricingPayload, validatePricingInput } from '@/features/admin-content/pricing/pricing-schema';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
function json(payload: Record<string, unknown>, status = 200) { return NextResponse.json(payload, { status, headers: { 'Cache-Control': 'private, no-store' } }); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) {
  const admin = await authorizeAdminRequest(request, true); if (!admin) return json({ ok: false, error: { code: 'forbidden', message: '無效的管理員 session 或請求驗證' } }, 403); const firebase = firebaseServer(); if (!firebase) return json({ ok: false, error: { code: 'service_unavailable', message: '資料服務尚未完成伺服器設定' } }, 503); const { id } = await context.params; const parsed = await readJsonObject(request, 64 * 1024); if (!parsed.ok) return json({ ok: false, error: { code: 'invalid_request', message: '資料格式不正確' } }, 400); const ref = firebase.db.collection('pricing_plans').doc(id); const current = await ref.get(); if (!current.exists || isDeleted(current.data())) return json({ ok: false, error: { code: 'not_found', message: '價目不存在' } }, 404); const currentVersion = Number.isInteger(current.data()?.version) ? Number(current.data()?.version) : 1; if (parsed.value.version != null && Number(parsed.value.version) !== currentVersion) return json({ ok: false, error: { code: 'conflict', message: '資料已被其他視窗更新，請重新載入後再儲存' } }, 409); const merged = { ...current.data(), ...parsed.value }; const validationError = validatePricingInput(merged); if (validationError) return json({ ok: false, error: { code: 'invalid_request', message: validationError } }, 400); try { await ref.update({ ...pricingPayload(merged), version: currentVersion + 1 }); await recordAdminAudit(firebase, admin, request, 'update', 'pricing_plan', id).catch(() => undefined); return json({ ok: true, data: { id, version: currentVersion + 1 } }); } catch { return json({ ok: false, error: { code: 'service_unavailable', message: '價目儲存失敗' } }, 503); }
}
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const admin = await authorizeAdminRequest(request, true); if (!admin) return json({ ok: false, error: { code: 'forbidden', message: '無效的管理員 session 或請求驗證' } }, 403); const firebase = firebaseServer(); if (!firebase) return json({ ok: false, error: { code: 'service_unavailable', message: '資料服務尚未完成伺服器設定' } }, 503); const { id } = await context.params; try { const ref = firebase.db.collection('pricing_plans').doc(id); const row = await ref.get(); if (!row.exists || isDeleted(row.data())) return json({ ok: false, error: { code: 'not_found', message: '價目不存在' } }, 404); await ref.update(deletedBy(admin)); await recordAdminAudit(firebase, admin, request, 'delete', 'pricing_plan', id).catch(() => undefined); return json({ ok: true, data: { id, deleted: true } }); } catch { return json({ ok: false, error: { code: 'service_unavailable', message: '價目刪除失敗' } }, 503); } }
