import type { Metadata } from 'next'; import { notFound } from 'next/navigation'; import { Header } from '@/components/Header'; import { Footer } from '@/components/Footer'; import { loadPricingPlans, loadService, loadServices, loadSettings } from '@/lib/data'; import Link from 'next/link';
import { SafeImage } from '@/components/SafeImage';
import { StructuredData } from '@/components/StructuredData';
import { breadcrumbSchema, serviceAdditionalDescription, serviceDescription, serviceSchema } from '@/lib/seo-schema';
import { buildSeoMetadata } from '@/lib/seo-metadata';
import { serviceDetailSections } from '@/lib/service-detail';
export async function generateStaticParams() { const values = (await loadServices()).map(({ slug }) => ({ slug })); return values.length ? values : [{ slug: 'zzzzzzzzzz' }]; }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const [service, site] = await Promise.all([loadService(slug), loadSettings()]); const title = service?.seoTitle?.trim() || (service ? `${service.name}｜${site.brandName}` : '服務項目'); const description = service?.seoDescription?.trim() || (service ? serviceDescription(service).replace(/\s+/g, '，') : site.servicesSubtitle); return buildSeoMetadata({ title, description, path: `/services/${slug}`, siteName: site.brandName, imageUrl: service?.imageUrl || site.ogImageUrl, imageAlt: service?.imageAlt || service?.name }); }
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [service,services,plans,siteSettings]=await Promise.all([loadService(slug),loadServices(),loadPricingPlans(),loadSettings()]);if(!service)return process.env.STATIC_EXPORT==='1'?null:notFound();const relatedPlans=plans.filter((plan)=>plan.relatedServiceSlugs?.includes(service.slug));const price=relatedPlans.length ? '' : service.priceLabel || (service.price == null ? '價格請洽詢' : `NT$ ${service.price.toLocaleString()}`);const relatedServices=services.filter((item)=>item.slug!==service.slug).slice(0,4);const additionalDescription=serviceAdditionalDescription(service);const detailSections=serviceDetailSections(service);const schemaService=relatedPlans.length?{...service,price:undefined,priceLabel:undefined}:service;return <><Header siteSettings={siteSettings}/><main id="main-content" tabIndex={-1} className="detail-page"><div className="container detail-layout"><div><StructuredData data={breadcrumbSchema([{name:'首頁',path:'/'},{name:'服務項目',path:'/services'},{name:service.name,path:`/services/${service.slug}`}])}/><nav className="breadcrumbs" aria-label="麵包屑"><Link href="/">首頁</Link><span aria-hidden="true">／</span><Link href="/services">服務項目</Link><span aria-hidden="true">／</span><span>{service.name}</span></nav><SafeImage className="detail-image" src={service.imageUrl} alt={`服務詳情圖片：${service.imageAlt || service.name}`} loading="eager" fetchPriority="high" /></div><article><StructuredData data={serviceSchema(schemaService, siteSettings)}/><span className="eyebrow">SERVICE</span><h1>{service.name}</h1><p className="detail-summary">{service.summary}</p>{additionalDescription&&<p className="detail-description">{additionalDescription}</p>}{relatedPlans.length ? <div className="detail-prices"><h2>相關價目</h2>{relatedPlans.map((plan)=><p key={plan.id}><span>{plan.name}</span><b>NT$ {plan.price.toLocaleString()}</b>{plan.durationMinutes != null && <small>{plan.durationMinutes} 分鐘</small>}</p>)}</div> : <>{service.durationMinutes != null&&<p>療程時間｜{service.durationMinutes} 分鐘</p>}<strong className="detail-price">{price}</strong></>}{detailSections.map(({title,text})=><section className="detail-section" key={title}><h2>{title}</h2><p>{text}</p></section>)}<Link className="btn" href={siteSettings.lineUrl}>立即預約　→</Link></article></div>{relatedServices.length>0&&<section className="related-services container" aria-labelledby="related-services-title"><h2 id="related-services-title">其他服務項目</h2><div className="related-services-grid">{relatedServices.map((item)=><Link className="related-service-card" href={`/services/${item.slug}`} key={item.id}><SafeImage src={item.imageUrl} alt={`相關服務：${item.imageAlt||item.name}`}/><span>{item.name}</span><small>{item.summary}</small></Link>)}</div></section>}</main><Footer siteSettings={siteSettings}/></>}
